# Generated by Django 5.2.6 on 2025-09-17 13:10

import apps.accounts.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveIndex(
            model_name='profile',
            name='profiles_locatio_64b8ec_idx',
        ),
        migrations.RemoveIndex(
            model_name='profile',
            name='profiles_experie_54377e_idx',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Available for job opportunities'),
        ),
        migrations.AddField(
            model_name='profile',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('employers_only', 'Employers Only')], default='public', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='github_url',
            field=models.URLField(blank=True, null=True, validators=[apps.accounts.utils.validate_github_url]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True, validators=[apps.accounts.utils.validate_linkedin_url]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/', validators=[django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='salary_expectation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['location', 'is_available'], name='profiles_locatio_69ff0f_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['experience_years', 'is_available'], name='profiles_experie_ac0503_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['visibility', 'is_available'], name='profiles_visibil_1af7f5_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['updated_at'], name='profiles_updated_7c22e2_idx'),
        ),
    ]
