# Generated by Django 5.2.6 on 2025-09-17 13:10

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'job_types',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('popularity_score', models.PositiveIntegerField(default=0, help_text='Calculated popularity')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'skills',
                'ordering': ['-popularity_score', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Skill Categories',
                'db_table': 'skill_categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='jobs.jobcategory')),
            ],
            options={
                'verbose_name_plural': 'Job Categories',
                'db_table': 'job_categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('responsibilities', models.TextField()),
                ('benefits', models.TextField(blank=True)),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('temporary', 'Temporary'), ('internship', 'Internship'), ('freelance', 'Freelance')], db_index=True, max_length=20)),
                ('experience_level', models.CharField(choices=[('entry', 'Entry Level'), ('junior', 'Junior'), ('mid', 'Mid Level'), ('senior', 'Senior'), ('lead', 'Lead/Principal'), ('executive', 'Executive')], db_index=True, max_length=20)),
                ('location', models.CharField(db_index=True, max_length=200)),
                ('remote_allowed', models.BooleanField(db_index=True, default=False)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('salary_currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('NGN', 'Nigerian Naira'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar')], default='USD', max_length=3)),
                ('salary_negotiable', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed'), ('on_hold', 'On Hold')], db_index=True, default='draft', max_length=20)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('is_urgent', models.BooleanField(default=False)),
                ('application_deadline', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('views_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('applications_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='companies.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_jobs', to=settings.AUTH_USER_MODEL)),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='companies.industry')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='jobs.jobcategory')),
                ('skills', models.ManyToManyField(blank=True, related_name='jobs', to='jobs.skill')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'db_table': 'jobs',
                'ordering': ['-is_featured', '-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('viewed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('referrer', models.URLField(blank=True, null=True)),
                ('duration', models.PositiveIntegerField(blank=True, help_text='View duration in seconds', null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_views', to='jobs.job')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job View',
                'verbose_name_plural': 'Job Views',
                'db_table': 'job_views',
            },
        ),
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('notes', models.TextField(blank=True, help_text='Personal notes about this job')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='jobs.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Job',
                'verbose_name_plural': 'Saved Jobs',
                'db_table': 'saved_jobs',
                'ordering': ['-saved_at'],
            },
        ),
        migrations.CreateModel(
            name='JobAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name for this alert', max_length=200)),
                ('keywords', models.CharField(blank=True, help_text='Comma-separated keywords', max_length=500)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('remote_only', models.BooleanField(default=False)),
                ('experience_levels', models.JSONField(blank=True, default=list)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('salary_currency', models.CharField(default='USD', max_length=3)),
                ('frequency', models.CharField(choices=[('immediate', 'Immediate'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_sent', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('jobs_sent_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('industries', models.ManyToManyField(blank=True, to='companies.industry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_alerts', to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(blank=True, to='jobs.jobcategory')),
                ('job_types', models.ManyToManyField(blank=True, to='jobs.jobtype')),
                ('skills', models.ManyToManyField(blank=True, to='jobs.skill')),
            ],
            options={
                'verbose_name': 'Job Alert',
                'verbose_name_plural': 'Job Alerts',
                'db_table': 'job_alerts',
            },
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skills', to='jobs.skillcategory'),
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cover_letter', models.TextField(blank=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='application_resumes/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('interview_scheduled', 'Interview Scheduled'), ('interview_completed', 'Interview Completed'), ('offer_made', 'Offer Made'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], db_index=True, default='pending', max_length=30)),
                ('notes', models.TextField(blank=True, help_text='Internal notes from recruiters')),
                ('score', models.PositiveIntegerField(blank=True, help_text='Internal scoring (1-10)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('applied_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Application',
                'verbose_name_plural': 'Job Applications',
                'db_table': 'job_applications',
                'ordering': ['-applied_at'],
                'indexes': [models.Index(fields=['status', 'applied_at'], name='job_applica_status_238d7a_idx'), models.Index(fields=['job', 'status'], name='job_applica_job_id_e29281_idx'), models.Index(fields=['applicant', 'status'], name='job_applica_applica_435597_idx'), models.Index(fields=['reviewed_at'], name='job_applica_reviewe_d8410b_idx'), models.Index(fields=['score'], name='job_applica_score_bef3b4_idx')],
                'unique_together': {('job', 'applicant')},
            },
        ),
        migrations.AddIndex(
            model_name='jobcategory',
            index=models.Index(fields=['parent', 'is_active'], name='job_categor_parent__f85dcf_idx'),
        ),
        migrations.AddIndex(
            model_name='jobcategory',
            index=models.Index(fields=['is_active', 'sort_order'], name='job_categor_is_acti_cbdaf9_idx'),
        ),
        migrations.AddIndex(
            model_name='jobview',
            index=models.Index(fields=['job', 'viewed_at'], name='job_views_job_id_994b7a_idx'),
        ),
        migrations.AddIndex(
            model_name='jobview',
            index=models.Index(fields=['ip_address', 'viewed_at'], name='job_views_ip_addr_b545f9_idx'),
        ),
        migrations.AddIndex(
            model_name='jobview',
            index=models.Index(fields=['user', 'viewed_at'], name='job_views_user_id_2dd5a6_idx'),
        ),
        migrations.AddIndex(
            model_name='jobview',
            index=models.Index(fields=['session_key', 'viewed_at'], name='job_views_session_60b9d9_idx'),
        ),
        migrations.AddIndex(
            model_name='savedjob',
            index=models.Index(fields=['user', 'saved_at'], name='saved_jobs_user_id_8ab2cc_idx'),
        ),
        migrations.AddIndex(
            model_name='savedjob',
            index=models.Index(fields=['job', 'saved_at'], name='saved_jobs_job_id_db6176_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='savedjob',
            unique_together={('user', 'job')},
        ),
        migrations.AddIndex(
            model_name='jobalert',
            index=models.Index(fields=['user', 'is_active'], name='job_alerts_user_id_904ac0_idx'),
        ),
        migrations.AddIndex(
            model_name='jobalert',
            index=models.Index(fields=['frequency', 'is_active'], name='job_alerts_frequen_c437ef_idx'),
        ),
        migrations.AddIndex(
            model_name='jobalert',
            index=models.Index(fields=['last_sent', 'is_active'], name='job_alerts_last_se_525ad5_idx'),
        ),
        migrations.AddIndex(
            model_name='jobalert',
            index=models.Index(fields=['created_at'], name='job_alerts_created_cc22c9_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', 'published_at'], name='jobs_status_697456_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['location', 'remote_allowed'], name='jobs_locatio_0b3018_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['job_type', 'status'], name='jobs_job_typ_f035dd_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['experience_level', 'status'], name='jobs_experie_c55d63_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['is_featured', 'status'], name='jobs_is_feat_c15b6d_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['application_deadline'], name='jobs_applica_13933b_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['salary_min', 'salary_max'], name='jobs_salary__0b1197_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['company', 'status'], name='jobs_company_0582d9_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['category', 'status'], name='jobs_categor_1a990f_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['industry', 'status'], name='jobs_industr_084702_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['views_count'], name='jobs_views_c_a7be5a_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['applications_count'], name='jobs_applica_0f4ed0_idx'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['category', 'is_active'], name='skills_categor_da0329_idx'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['popularity_score', 'is_active'], name='skills_popular_15e45d_idx'),
        ),
    ]
